### ISSUE TITLE
Code Review - bentohset

### ISSUE THREAD

**Issue by R-Ramana** [AY2223S2-CS2113-T11-2/tp#113]
1. Remove code that are unused (don't comment them out)

2. Unsure what the `<p>` tag refers to here. Appears in several areas.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/54029207/229076412-b33514f7-fd2d-47e2-a0c5-614c27716faf.png">

3. This is [arrowhead coding](https://nus-cs2113-ay2223s2.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-deep-nesting). Please try to refactor

<img width="678" alt="image" src="https://user-images.githubusercontent.com/54029207/229076747-7ddd5524-b3ba-4480-9453-bd9de12e02f8.png">

**Comment by bentohset** [comment]
#167
