### ISSUE TITLE
[PE-D][Tester D] Formatting of `help` cmd

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T11-2/tp#122]
![image.png](https://raw.githubusercontent.com/nikkiDEEE/ped/main/files/335bbcd2-dcce-4c91-99de-c05c82a40524.png)

 
The description of cods is out of divider Len

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: nikkiDEEE/ped#3

**Comment by Ansenn** [comment]
- Increase divider length
- Decrease length of help messages, put sentence into 2 lines if needed
- Ensure formatting is readable
