### ISSUE TITLE
[PE-D][Tester C] list command showing null

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T11-2/tp#123]
![image.png](https://raw.githubusercontent.com/darrenangwx/ped/main/files/1097b18c-bc36-4f11-964d-8d159e43f7ce.png)

![image.png](https://raw.githubusercontent.com/darrenangwx/ped/main/files/3086adc4-ade3-4ace-96af-2dbbfe112ee2.png)

![image.png](https://raw.githubusercontent.com/darrenangwx/ped/main/files/cb497e2a-a25d-4cb8-b136-455b82a8c1f8.png)

I've added modules according to the user guide, but I am unable to see any modules when 'list' command was typed. I think this bug only occurs when using the  `taken` command and I add in a module that does not exists (e.g. abcde). For `plan` adding in a module that does not exist will still allow me to list all modules.  

I think if I added mods that are not in NUSMods, the `list` command will show null as a result.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: darrenangwx/ped#1

**Comment by bentohset** [comment]
add isValid checker with moduleRetriever whenever module is added

**Comment by bentohset** [comment]
fixed with #174 
can double check if still return null @Ansenn

**Comment by Ansenn** [comment]
Fixed with #185
