### ISSUE TITLE
[PE-D][Tester D] Integer with trailing white space not accepted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T11-2/tp#127]
![image.png](https://raw.githubusercontent.com/nikkiDEEE/ped/main/files/40ccfc42-9ea0-426c-9de6-6921f77496fe.png)

Integer has been keyed in but it says `c/ must be an integer`.

Perhaps use a string manipulation technique like .trim() to remove the trailing whitespace.

Either that or the error prompt has to be changed from "... valid integer" to " ... valid input" and prompt the user to not leave any leading/ trailing white spaces.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: nikkiDEEE/ped#5

**Comment by TayJiunYuan** [comment]
Resolved, thanks for the issue!
