### ISSUE TITLE
[PE-D][Tester B] No details under valid module code

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T11-2/tp#132]
![2222.png](https://raw.githubusercontent.com/TopGun2001/ped/main/files/feaa1db0-5187-4eeb-adda-06ee6280e791.png)

There is a module named ES2631 but there is no information regarding the module. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: TopGun2001/ped#5

**Comment by Ansenn** [comment]
Fixed with #185
