### ISSUE TITLE
[PE-D][Tester C] Adding extra space to end of module name will result in the list showing null 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T11-2/tp#133]
![image.png](https://raw.githubusercontent.com/darrenangwx/ped/main/files/c55c456e-1f32-4d1d-b9fb-f9b6ed50feb2.png)

As seen in the image, I've added a module with extra spaces at the end of the name. the result is that the list will show `null`.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: darrenangwx/ped#2

**Comment by bentohset** [comment]
duplicate bug
