### ISSUE TITLE
[PE-D][Tester B] Same Input Different Output

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T11-2/tp#135]
![IO.png](https://raw.githubusercontent.com/TopGun2001/ped/main/files/7daad41b-5fd2-4769-9888-83187c3d201b.png)

Technically these are the same inputs but we get different outputs. It's recommended to trim out the extra spaces entered by the user accidentally.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: TopGun2001/ped#6

**Comment by TayJiunYuan** [comment]
resolved
