### ISSUE TITLE
[PE-D][Tester A] Adds a module to the year of 206 (expected error)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T11-2/tp#139]
The program does not validate year when module was taken 

Expected: error saying 206 is not a valid year, (expected range is 1-4 year)
Actual: printed that the module was successfully added

![Bug3.png](https://raw.githubusercontent.com/DavidVin357/ped/main/files/c346eeaf-93a0-47b0-b8ef-b417ab398eba.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: DavidVin357/ped#3

**Comment by bentohset** [comment]
duplicate bug
