### ISSUE TITLE
[PE-D][Tester B] No modules taken but 6 MC earned?

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T11-2/tp#145]
![111.png](https://raw.githubusercontent.com/TopGun2001/ped/main/files/ddead505-8129-4c39-9a71-bbbdd7576075.png)

There are no modules under 'Taken' but number of MCs taken is 6. 

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: TopGun2001/ped#9

**Comment by TayJiunYuan** [comment]
MCs Taken refers to all MCs, including both core mods and electives. Taken only shows taken core modules.
