### ISSUE TITLE
[PE-D][Tester C] Program failed to start 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T11-2/tp#146]
![image.png](https://raw.githubusercontent.com/darrenangwx/ped/main/files/7c91ba88-4575-473f-9d17-405e921c01c7.png)

When the file content is modified, it seems like invalid lines were not handled to ensure that the program ignore those lines and cleans the file. I received an ArrayIndexOutOfBoundsException instead.

This is the inputs I used for reference

![image.png](https://raw.githubusercontent.com/darrenangwx/ped/main/files/c3db08cb-c147-4306-8682-a8784fe4502b.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: darrenangwx/ped#4

**Comment by TayJiunYuan** [comment]
Correct usage of editing txt file is added to the UG.
