### ISSUE TITLE
[PE-D][Tester C] status and details command not working without internet connection

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T11-2/tp#150]
![image.png](https://raw.githubusercontent.com/darrenangwx/ped/main/files/23fca6f1-5569-422e-9fdc-4e47823cfa03.png)

As seen above, if I do not have any internet connection, I am unable to see my status or any module information

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: darrenangwx/ped#5

**Comment by TayJiunYuan** [comment]
API call cannot work without internet, will address in UG

**Comment by bentohset** [comment]
#193
