### ISSUE TITLE
[PE-D][Tester D] Need to capitalise the `Name`

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T11-2/tp#155]
![image.png](https://raw.githubusercontent.com/nikkiDEEE/ped/main/files/dcad5482-5d3d-47d1-b9c0-4195997388c0.png)

Should be `NAME` I assume.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: nikkiDEEE/ped#12

**Comment by TayJiunYuan** [comment]
fixed
