### ISSUE TITLE
[PE-D][Tester C] Unclear error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T11-2/tp#156]
![image.png](https://raw.githubusercontent.com/darrenangwx/ped/main/files/d8f9354b-9cd7-4b82-8de5-20d45784412a.png)

Perhaps a more clearer error message would help me understand what the error was instead of `For input string: "  1".`

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: darrenangwx/ped#7

**Comment by bentohset** [comment]
duplicate bug
