### ISSUE TITLE
[PE-D][Tester A] When lowercase grade put in penus.txt, it is not reflected as others

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T11-2/tp#161]
penus.txt before startup (with lowercase "a"):

"
User ###  David ### Electrical Engineering

Taken ### EE2026 ### 1 ### 1 ### A-

Taken ### MA1512 ### 4 ### 2 ### **a**
"

Expected: **a** is converted to A as with other lowercase grades which are put with taken

Actual: **a** is reflected as it is

![Bug10.png](https://raw.githubusercontent.com/DavidVin357/ped/main/files/f8a56b88-526a-4d7b-bd73-3eb266fe12dd.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: DavidVin357/ped#9

**Comment by bentohset** [comment]
convert to uppercase when initialising app
