### ISSUE TITLE
DG Issues

### ISSUE THREAD

**Issue by R-Ramana** [AY2223S2-CS2113-T11-2/tp#91]
Good Effort on the DG! I have listed some feedback for the DG

1. Should commons be referenced by something, like `Main` maybe? 
<img width="342" alt="image" src="https://user-images.githubusercontent.com/54029207/228723790-0e2d784a-fe4c-4bd0-9c23-7f467b4cc706.png">

2. This is a non-standard representation of the class diagram. [Refer here to update](https://github.com/nus-cs2113-AY2122S1/forum/issues/114). Same for subsequent class diagrams
<img width="416" alt="image" src="https://user-images.githubusercontent.com/54029207/228724039-a76d44f8-4696-4095-99a1-e8bb63604a67.png">

3. Try not to put the description in the middle, it is rather ambiguous as to where it belongs. 
<img width="402" alt="image" src="https://user-images.githubusercontent.com/54029207/228724736-92aee929-d165-4408-aedf-9451c0b79d21.png">

4. I think there are missing colons in the sequence diagrams and under the UI, the activation bar needs to be completely started. Likewise in the subsequent diagrams.
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/54029207/228725169-24468d55-55f6-4b26-b68d-1213e86f4165.png">

5. Self-invocation is missing an activation bar and I am unsure what the floating arrows are pointing to. This is recurring in the other sequence diagrams as well.
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/54029207/228726599-1f1d6d3a-f75e-48f1-bd44-b8618338cf04.png">

6. Unsure about the following. I believe they arose from merge conflicts, please ensure they are removed.
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/54029207/228726788-0eab20e1-1d68-4bce-9729-b65457f0335d.png">
<img width="595" alt="image" src="https://user-images.githubusercontent.com/54029207/228726848-fd16f4c6-55ac-40cc-af18-6908c24567d4.png">

**Comment by bentohset** [comment]
For no. 3, how do you put the description at the head of the arrow for plantUML?

**Comment by bentohset** [comment]
#92
